name: Run Tests

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    test:
        strategy:
            matrix:
                runner:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
                include:
                    - runner: ubuntu-latest
                      platform: Linux
                    - runner: windows-latest
                      platform: Windows
                    - runner: macos-latest
                      platform: macOS

        name: (${{ matrix.platform }}) Run Tests
        runs-on: ${{ matrix.runner }}
        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build & Test
              run: |
                  python -m pip install ninja
                  cmake -B build -G Ninja -DTBDD_GENERATE_TEST_RUNNER=ON && \
                  cmake --build build && \
                  ctest --test-dir build --verbose -C Debug -O ${{ matrix.platform }}.ctest.log

            - name: Upload Test Results
              uses: actions/upload-artifact@v4
              with:
                  path: build/ctest.log
                  if-no-files-found: ignore
                  retention-days: 7
                  overwrite: true
